version: '3.7'

services: 
  client_react_store:
    container_name: client_react_store
    build:
      context: Client/
      dockerfile: Dockerfile
    ports: 
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes: 
      - ./Client:/usr/src/app
      - /usr/src/app/node_modules